### ISSUE TITLE
make: *** No rule to make target `Release/obj.target/fdblib/src/FdbV8Wrapper.o', needed by `Release/fdblib.node'.  Stop.

### ISSUE THREAD

**Issue by ericsoderberghp** [josephg/node-foundationdb#15]
On MacOS with node v10, I installed FoundationDB [CLI 5.1 (v5.1.7)], and I'm seeing this error when running `yarn add foundationdb`:

make: *** No rule to make target `Release/obj.target/fdblib/src/FdbV8Wrapper.o', needed by `Release/fdblib.node'.  Stop.

Here's the whole output:

```
error /Users/ericsoderberg/Documents/git/grommet2/poke-orgs/node_modules/foundationdb: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/ericsoderberg/Documents/git/grommet2/poke-orgs/node_modules/foundationdb
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v10.0.0/node-v10.0.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.0.0/node-v10.0.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.0.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.0.0/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ericsoderberg/Documents/git/grommet2/poke-orgs/node_modules/foundationdb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ericsoderberg/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ericsoderberg/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ericsoderberg/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/ericsoderberg/Documents/git/grommet2/poke-orgs/node_modules/foundationdb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target `Release/obj.target/fdblib/src/FdbV8Wrapper.o', needed by `Release/fdblib.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/Cellar/node/10.0.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ericsoderberg/Documents/git/grommet2/poke-orgs/node_modules/foundationdb
```

I'm happy to help debug/triage with any pointers.

**Comment by josephg** [comment]
Oh oops my bad. I made some project configuration changes and the bundle didn't have the C++ files in it anymore.

Should be fixed now!
